// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjgbxjjwmhcmsunyjtpr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqZ2J4amp3bWhjbXN1bnlqdHByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyOTYzMjgsImV4cCI6MjA2Mjg3MjMyOH0.cNFCu4fIw1k-7Yfuym8GT_uYFYTXcd91l5XEirze484";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);